# fly.toml app configuration file generated for damp-meadow-3928 on 2023-11-10T11:01:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-meadow-3928"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
